# Generated by Django 2.0.2 on 2018-03-12 14:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180312_2226'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
