# Generated by Django 2.0.2 on 2018-03-11 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('des', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('birthday', models.DateTimeField(blank=True)),
                ('tel', models.IntegerField(blank=True)),
                ('sex', models.IntegerField(blank=True, default=0)),
                ('email', models.EmailField(max_length=254)),
                ('describe', models.CharField(blank=True, max_length=300)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('latest_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('des', models.CharField(max_length=200, null=True)),
                ('permission', models.ManyToManyField(to='user.Permission')),
            ],
            options={
                'db_table': 'UsersGroup',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UsersGroup'),
        ),
    ]
